fix test error check

diff --git a/lib/Builtins/Tests/01_ShuntingYard/run b/lib/Builtins/Tests/01_ShuntingYard/run
--- a/lib/Builtins/Tests/01_ShuntingYard/run
+++ b/lib/Builtins/Tests/01_ShuntingYard/run
@@ -4,8 +4,9 @@ set -e
 cd Tests/01_ShuntingYard
 for s in *.5D
 do
+	echo "= $s"
 	er="${s%.5D}.expectedResult"
 	gr="${s%.5D}.gotResult" 
-	./testShuntingYard "${s}" >"${gr}" || echo "failed: $s">&2
+	./testShuntingYard "${s}" >"${gr}" || (echo "failed: $s">&2 ; false)
 	diff -upr "${gr}" "${er}"
 done
